version: '2'

services:
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./www:/var/www/html/wp-content
    networks:
      - proxy
      - default
    environment:
      VIRTUAL_HOST: example.localhost
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  pma:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    networks:
      - proxy
      - default
    environment:
      VIRTUAL_HOST: pma.example.localhost
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G

networks:
  proxy:
    external:
      name: reverse-proxy
